version: '3.1'

services:
  url_lookup_service:
    build: .
    # image: registry.gitlab.com/idgst/springboot-mongo-demo:latest
    restart: always
    container_name: url_lookup_service
    ports:
      - 8080:8080
    working_dir: $HOME/coding_excercise/app
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo
    container_name: mongodb
    ports:  
         - 27017:27017
    volumes:
      - $HOME/data/mongo_data:/data/db
      - $HOME/data/mongo_bkp:/data/bkp
    restart: always